### ISSUE TITLE
Status code undefined

### ISSUE THREAD

**Issue by joaogbcravo** [skhatri/grunt-nexus-deployer#11]
Nexus deployer it's not consistent. Sometimes it uploads all the files correctly. But in the majority of the times it fails with a status code "undefined". This happens sometimes with the metadata.xml file but also with the pom.xml.

It's something related with the "status" variable in the childProcess.stdout.on or childProcess.on function.

Full output:
09:16:17 -------------------------------------------
09:16:17 >> Artifact Upload failed
09:16:17 >> Status code undefined for http://nexus/content/repositories/yum_releases/group/project/maven-metadata.xml
09:16:17 Warning: Task "nexusDeployer:release" failed. Use --force to continue.

**Comment by daulphinus01** [comment]
Hey guys,
Am having the same problem when i try to upload my "projet_bidon.zip" to nexus and i can't how you guys fixed the same problem.
Any help ?!

**Comment by joaogbcravo** [comment]
Hey @daulphinus01 . We have fixed with #12

**Comment by daulphinus01** [comment]
@joaogbcravo , thank you for the response.
In my "node_modules/grunt-nexus-deployer/tasks/lib/index.js", it uses "close" instead of "exit" but still i get the same error.

Here is my nexusDeploy config in Gruntfile.js:

nexusDeployer: {
      release: {
        options: {
          groupId: "com.my.group.id",
          artifactId: "com-my-group-id",
          version: '<%= yeoman.pkg.version %>',
          packaging: 'zip',
          auth: {
            username: 'username',
            password: 'userpwd'
          },
          pomDir: '<%= yeoman.dist %>/pom',
          url: 'http://IP_ADRESS:PORT/nexus/content/repositories/my-snapshots-repo',
          artifact: '<%= yeoman.dist %>' + '/' + '<%= yeoman.pkg.name %>' + '-' + '<%= yeoman.pkg.version %>' + '.zip',
          noproxy: 'localhost',
          cwd: '',
          parallel: false,
          quiet: false
        }
      }
    }


And here is what i'm getting as error:

>> Artifact Upload failed
>> Status code undefined for http://IP_ADRESS:PORT/nexus/content/repositories/my-snapshots-repo/com/my/group/id/com-my-group-id/maven-metadata.xml
Warning: Task "nexusDeployer:release" failed. Use --force to continue.

Aborted due to warnings.

Thanks for your time

**Comment by drvarma** [comment]
@daulphinus01 
I'm having the same issue, but it was resolved when change the childProcess.on() as

childProcess.on('close', function (code) {
                if (code != 0 || (status != "200" && status != "201")) {
                    cb("Status code " + status + " for " + targetUri, null);
                } else {
                    cb(null, "Ok");
                }
            });

**Comment by FaJo8080** [comment]
Same issue on 0.10

**Comment by cmacdonnacha** [comment]
Same issue on 0.2.2
