### ISSUE TITLE
Templates don't get populated

### ISSUE THREAD

**Issue by sbdev** [skhatri/grunt-nexus-deployer#13]
Looks like although ejs.render receives the expected options here
https://github.com/skhatri/grunt-nexus-deployer/blob/master/tasks/lib/index.js#L19
the values are not inserted in the template which results not populated.

I suspect ejs doesn't support (anymore?) the `ejs.open` and `ejs.close` configs.
If I revert to the "classic" ejs pattern (`<artifactId><%=artifactId%></artifactId>`) all works fine.

Thanks!!!

**Comment by invasionofsmallcubes** [comment]
I'm having the same problem. My configuration is:
```
       nexusDeployer: {
            release: {
                options: {
                    groupId: "com.group",
                    artifactId: "brg-ui-mauser-bo",
                    version: "0.0.2",
                    name: "MAUSER Bo",
                    packaging: 'tar',
                    url: getRepository(),
                    debug: true,
                    artifact: "brg-ui-mauser-bo-0.0.2.tar",
                    pomDir: '.',
                    auth: {
                        username: 'deployment',
                        password: 'xxxxxxx'
                    }
                }
            }
        }
```
but the pom.xml is:
```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>{{=groupId}}</groupId>
<artifactId>{{=artifactId}}</artifactId>
<version>{{=version}}</version>
<packaging>{{=packaging}}</packaging>
</project>
```
but I don't understand what I'm doing wrong.

**Comment by doronha** [comment]
Hi,

I've downloaded the package today and still the template are not populated 

Doron
